<?php

namespace Runalyze\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PluginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PluginRepository extends EntityRepository
{
    /*
     * Get all configurations for an account
     */
    public function findAllActiveForAccount($accountid)
    {  
        return $this->createQueryBuilder('p')
        ->select('p')
        ->where('p.accountid = :accountid')
        ->andWhere('p.active >= 1')
        ->setParameter('accountid', $accountid)
        ->getQuery()->getResult();
    }
}
