<?php

namespace Runalyze\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportRepository extends EntityRepository
{
    public function getShortSport($accountid) {
        return $this->createQueryBuilder('s')
        ->select('s.id')
        ->where('s.accountid = :accountid')
        ->andWhere('s.short = 1')
        ->setParameter('accountid', $accountid)
        ->getQuery()->getResult();
    }
            
}
